language: generic
os:
  - linux
services:
  - docker

before_install:
  - docker build -t nullpunkt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nullpunkt/docker-react npm run test
